name: ipotato_timer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.7
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  assets_audio_player: ^3.1.1
  flutter_native_splash: ^2.3.10
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mobx_codegen: ^2.6.0+1
  drift_dev: ^2.16.0



flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/





flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  image_dark: assets/images/icon.png

  android_12:
    image: assets/images/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon.png
    icon_background_color_dark: "#121212"

  web: false