// Mocks generated by Mockito 5.4.4 from annotations
// in ipotato_timer/test/src/features/add_task/presentation/store/add_task_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i5;
import 'package:ipotato_timer/src/core/error/custom_error.dart' as _i6;
import 'package:ipotato_timer/src/features/add_task/domain/repositories/add_task_repository.dart'
    as _i2;
import 'package:ipotato_timer/src/features/add_task/domain/usecases/add_task_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddTaskRepository_0 extends _i1.SmartFake
    implements _i2.AddTaskRepository {
  _FakeAddTaskRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddTaskUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTaskUseCase extends _i1.Mock implements _i3.AddTaskUseCase {
  MockAddTaskUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddTaskRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddTaskRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddTaskRepository);

  @override
  _i4.Future<_i5.Either<_i6.CustomError, void>> call(
          _i3.AddTaskParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.CustomError, void>>.value(
            _i7.dummyValue<_i5.Either<_i6.CustomError, void>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.CustomError, void>>);
}
