// Mocks generated by Mockito 5.4.4 from annotations
// in ipotato_timer/test/src/features/task_list/domain/usecases/task_list_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:ipotato_timer/src/core/error/custom_error.dart' as _i5;
import 'package:ipotato_timer/src/features/add_task/data/models/task_model.dart'
    as _i6;
import 'package:ipotato_timer/src/features/task_list/domain/repositories/task_list_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskListRepository extends _i1.Mock
    implements _i2.TaskListRepository {
  MockTaskListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.CustomError, List<_i6.TaskModel>>> taskList() =>
      (super.noSuchMethod(
        Invocation.method(
          #taskList,
          [],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.CustomError, List<_i6.TaskModel>>>.value(
            _i7.dummyValue<_i4.Either<_i5.CustomError, List<_i6.TaskModel>>>(
          this,
          Invocation.method(
            #taskList,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.CustomError, List<_i6.TaskModel>>>);
}
